language: node_js
node_js:
  - "10"
  - "11"
before_script:
  - npm run coverage
after_script:
  - npm run codeclimate
notifications:
  slack:
    rooms:
      weirdunicorn:S7RWHqp3eUYiYBusZOzXytvR#join-challenge
    on_success: change
