language: node_js
node_js:
  - "10"
  - "11"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_success:
  - npm run coverage
notifications:
  slack:
    rooms:
      gorlifsense:S7RWHqp3eUYiYBusZOzXytvR#join-challenge
    on_success: change
